# Generated by Django 4.2.6 on 2023-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=20),
        ),
    ]
