# Generated by Django 4.2.5 on 2023-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Address",
            new_name="UserAddress",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[("renter", "Renter"), ("owner", "Owner")], max_length=20
            ),
        ),
    ]
