# Generated by Django 4.2.6 on 2023-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_alter_booking_end_date_alter_booking_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agreement",
            old_name="property",
            new_name="booking",
        ),
    ]
