# Generated by Django 4.2.6 on 2023-10-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_rename_property_agreement_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyrequest",
            name="request_rent_amount",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
