# Generated by Django 4.2.5 on 2023-10-06 06:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0003_propertyaddress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="requested_date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="approved_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="leaving_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="property",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 10, 6, 6, 33, 26, 389543, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2023, 10, 6, 6, 33, 40, 407456, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agreement",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="property.booking"
            ),
        ),
        migrations.CreateModel(
            name="PropertyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_start_date", models.DateField()),
                ("requested_end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="property.booking",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="property.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
