# Generated by Django 4.2.5 on 2023-10-06 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_rename_requested_date_booking_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyrequest",
            old_name="requested_end_date",
            new_name="request_end_date",
        ),
        migrations.RenameField(
            model_name="propertyrequest",
            old_name="requested_start_date",
            new_name="request_start_date",
        ),
    ]
