# Generated by Django 4.2.6 on 2023-10-12 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_propertyrequest_request_rent_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="document",
            field=models.FileField(upload_to="aggrement/renter"),
        ),
        migrations.CreateModel(
            name="PropertyRequestResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rent_amount", models.PositiveIntegerField(null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("document", models.FileField(upload_to="aggrement/owner")),
                (
                    "property_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.propertyrequest",
                    ),
                ),
            ],
        ),
    ]
