# Generated by Django 4.2.5 on 2023-10-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0005_rename_requested_end_date_propertyrequest_request_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
