# Generated by Django 4.2.6 on 2023-10-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_alter_agreement_document_propertyrequestresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="propertyrequest",
            name="booking",
        ),
        migrations.AddField(
            model_name="booking",
            name="property_request_response",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="property.propertyrequestresponse",
            ),
        ),
    ]
