# Generated by Django 4.2.6 on 2023-10-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0006_remove_booking_end_date_remove_booking_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="property_request_response",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="property.propertyrequest",
            ),
        ),
        migrations.DeleteModel(
            name="PropertyRequestResponse",
        ),
    ]
