# Generated by Django 4.2.6 on 2023-10-13 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0007_alter_booking_property_request_response_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PropertyRequest",
            new_name="PropertyRequestResponse",
        ),
    ]
