# Generated by Django 4.2.6 on 2023-10-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0008_rename_propertyrequest_propertyrequestresponse"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyrequestresponse",
            old_name="request_end_date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="propertyrequestresponse",
            old_name="request_rent_amount",
            new_name="rent_amount",
        ),
        migrations.RenameField(
            model_name="propertyrequestresponse",
            old_name="request_start_date",
            new_name="start_date",
        ),
        migrations.AlterField(
            model_name="propertyrequestresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("responsed", "Responsed"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
