# Generated by Django 4.2.6 on 2023-10-16 07:07

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "property",
            "0009_rename_request_end_date_propertyrequestresponse_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyrequestresponse",
            name="request_token",
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterUniqueTogether(
            name="propertyrequestresponse",
            unique_together={("request_token", "user", "property", "created_at")},
        ),
        migrations.RemoveField(
            model_name="propertyrequestresponse",
            name="status",
        ),
    ]
