# Generated by Django 4.2.6 on 2023-10-16 09:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("property", "0010_propertyrequestresponse_request_token_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyrequestresponse",
            old_name="property",
            new_name="request_response_property",
        ),
        migrations.AlterUniqueTogether(
            name="propertyrequestresponse",
            unique_together={
                ("request_token", "user", "request_response_property", "created_at")
            },
        ),
    ]
