# Generated by Django 4.2.6 on 2023-10-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0011_rename_property_propertyrequestresponse_request_response_property_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="propertyrequestresponse",
            old_name="request_response_property",
            new_name="property",
        ),
        migrations.AlterUniqueTogether(
            name="propertyrequestresponse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="propertyrequestresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("responsed", "Responsed"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
