# Generated by Django 4.2.6 on 2023-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0013_alter_propertyrequestresponse_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyrequestresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("responsed", "Responsed"),
                    ("rejected", "Rejected"),
                    ("approved", "Approved"),
                    ("left", "Lefted"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
