# Generated by Django 4.2.6 on 2023-10-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "property",
            "0015_rename_property_propertyrequestresponse_request_response_property_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="document",
            field=models.FileField(null=True, upload_to="bills"),
        ),
    ]
